openapi: 3.0.0
info:
  title: QuoteAPI
  version: 0.0.1

paths:
  /v1/quote:
    get:
      description: Get a random quote
      summary: Random quote
      operationId: v1Random
      responses:
        "200":
          description: Quote response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quote"
  /v1/author/{author}:
    get:
      description: Get a random quote by specified author
      summary: Random quote by author
      operationId: v1AuthorRandom
      parameters:
        - name: author
          in: path
          required: true
          schema:
            type: string
            example: "shakespeare" # TODO: Or am I gonna use full name?
      responses:
        "200":
          description: Quote response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quote"
        "404":
          description: Author not found
  /v1/tag/{tag}:
    get:
      description: Get a random quote with specified tag
      summary: Random quote by tag
      operationId: v1TagRandom
      parameters:
        - name: tag
          in: path
          required: true
          schema:
            type: string
            example: "motivational"
      responses:
        "200":
          description: Quote response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quote"
        "404":
          description: Quote not found

components:
  schemas:
    Quote:
      type: object
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
          example: "To be, or not to be, that is the question"
        author:
          type: string
          example: "William Shakespeare"
        tags:
          type: array
          items:
            type: string
          example: [ "powerful", "deep", "motivational" ]


